SELECT 'LAST LOG APPLIED : ' LOGS, TO_CHAR(NEXT_TIME,'DD-MON-YY:HH24:MI:SS') TIME
FROM V$ARCHIVED_LOG
WHERE SEQUENCE# = (SELECT MAX(SEQUENCE#) FROM V$ARCHIVED_LOG WHERE APPLIED='YES')
UNION
SELECT 'LAST LOG RECEIVED : ' LOGS, TO_CHAR(NEXT_TIME,'DD-MON-YY:HH24:MI:SS') TIME
FROM V$ARCHIVED_LOG
WHERE SEQUENCE# = (SELECT MAX(SEQUENCE#) FROM V$ARCHIVED_LOG);
