COLUMN DDL FORMAT A300
SET HEAD OFF
SET PAGES 0
SET FEEDBACK OFF
SET LONG 9999999
SET LINES 300
SET TRIMSPOOL ON
SET VERIFY OFF

EXEC DBMS_METADATA.SET_TRANSFORM_PARAM (DBMS_METADATA.SESSION_TRANSFORM, 'SQLTERMINATOR', TRUE);
EXEC DBMS_METADATA.SET_TRANSFORM_PARAM (DBMS_METADATA.SESSION_TRANSFORM, 'PRETTY', TRUE);
 
WITH objroles AS
    ( SELECT role
      FROM DBA_ROLES
      WHERE ROLE IN ( '&1'))
SELECT DBMS_METADATA.GET_DDL('ROLE', role) AS ddl
FROM  objroles 
UNION ALL
SELECT DBMS_METADATA.GET_GRANTED_DDL('ROLE_GRANT', role) AS ddl
FROM   objroles WHERE role IN (SELECT grantee FROM dba_role_privs)
UNION ALL
SELECT DBMS_METADATA.GET_GRANTED_DDL('SYSTEM_GRANT', role) AS ddl
FROM   objroles WHERE role IN (SELECT grantee FROM dba_sys_privs)
UNION ALL
SELECT DBMS_METADATA.GET_GRANTED_DDL('OBJECT_GRANT', role) AS ddl
FROM   objroles WHERE role IN (SELECT grantee FROM dba_tab_privs);
