COMPUTE SUM LABEL "SUM" OF PERCENT_SPACE_USED ON REPORT
COMPUTE SUM OF PERCENT_SPACE_RECLAIMABLE ON REPORT
COMPUTE SUM OF NUMBER_OF_FILES ON REPORT
BREAK ON REPORT
SET LINES 121
SELECT *
FROM V$RECOVERY_AREA_USAGE
/
